### ISSUE TITLE
Release v1.6.0

### ISSUE THREAD

**Issue by garbas** [plone/mockup#329]
# Changelog
- [ ] NEW: remove ace as code editor and use codemirror (used in the dev tools for both Firefox and Chrome, Light Table, Adobe Brackets, Bitbucket, and many other projects.)
- [ ] NEW: customViewFields (on collection content type) should be using AjaxSelectWidget
- [ ] NEW: recurrence widget reimplement (reference to discussion, another mockup ticket)
- [ ] NEW: robot tests for ajax select widget
- [ ] NEW: robot tests for related items widget
- [ ] NEW: robot tests for rich widget
- [ ] DOCS: getting started page need to be reviewed and restructured a bit
- [ ] DOCS: same as for getting started page needs to be done for tutorial page
- [ ] DOCS: backdrop pattern description needed
- [ ] DOCS: filemanager pattern description needed
- [ ] DOCS: formautofocus pattern description needed
- [ ] DOCS: patterns listing needs to be sorted with some fluid grid system like masonary
- [ ] TESTS: mockup-core is at 94% tests coverage make it be 100%
- [ ] TESTS: tests/iframe-test.js is skipped from test suite
- [ ] TESTS: tests should pass on IE8/9/10
- [ ] BUG: RichText widget for archetypes
- [ ] BUG: formunloadalert.js: don't warn if nothing changed ( #159 )
- [ ] BUG: querystring widget bugs ( #226 )
- [x] BUG: AjaxSelectWidget not showing elements properly ( #228 )
- [x] BUG: make it possible to select single related item in relateditems widget ( #240 )
- [ ] NEW: rewrite plone.app.search's javascript ( #301, @amleczko )
- [x] SETUP: add JavaScript Code Style checker integration ( #331, @garbas )
- [x] SETUP: possibility to bootstrap using nix ( plone/mockup-core#6, @garbas )
- [x] BUG: remove old tinymce javascript and old widgets styles ( @garbas )
- [x] BUG: plone.app.widgets conflicts with RichText widget ( #330, @garbas)
- [x] CLEANUP: move picture pattern to mockup-extras ( #343, @garbas )
